/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.restaurant;

import Clients.ClientThread;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Vita
 */
public class ActiveTablesFrame extends javax.swing.JFrame {
    private final ClientThread ct;
    LinkedList<Double> tables;
    ArrayList<JPanel> panels = new ArrayList<JPanel>() ;
    ArrayList<JLabel> labels = new ArrayList<JLabel>();
    /**
     * Creates new form ActiveTablesFrame
     * @param ct
     * @param list
     */
    public ActiveTablesFrame(ClientThread ct, Iterable list) {   
        this.ct = ct;
        this.tables = (LinkedList<Double>) list;
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension screenSize = kit.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        this.setLocation (screenWidth / 2 - this.getWidth()/2, screenHeight / 2 - this.getHeight() / 2);

        addPanels();
        addLabels();
        
        String s1 = tables.get(0).toString();
        this.tableNumber.setText(s1.substring(0, s1.length()-2));
        
        for(int i = 1; (i<tables.size())&&(i<21); i++){
            final JLabel jl = this.labels.get(i);
            String s = tables.get(i).toString();
            jl.setText(s.substring(0, s.length()-2));       
            JPanel jp = this.panels.get(i); 
            jp.setBackground(new java.awt.Color(153, 153, 255));
            jp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            
            jp.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    onClicked(evt, jl);
                }
            });                 
            //this.tableCollection.add(jp);
            //jp.add(jl);
    } 
    }

    private void onClicked(java.awt.event.MouseEvent evt, JLabel jl) {  
        new PaymentFrame(ct, Integer.parseInt(jl.getText().toString())).setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JButton();
        tableCollection = new javax.swing.JPanel();
        table = new javax.swing.JPanel();
        tableNumber = new javax.swing.JLabel();
        j1 = new javax.swing.JPanel();
        tableNumber1 = new javax.swing.JLabel();
        j2 = new javax.swing.JPanel();
        tableNumber2 = new javax.swing.JLabel();
        j3 = new javax.swing.JPanel();
        tableNumber3 = new javax.swing.JLabel();
        j4 = new javax.swing.JPanel();
        tableNumber4 = new javax.swing.JLabel();
        j5 = new javax.swing.JPanel();
        tableNumber5 = new javax.swing.JLabel();
        j6 = new javax.swing.JPanel();
        tableNumber6 = new javax.swing.JLabel();
        j7 = new javax.swing.JPanel();
        tableNumber7 = new javax.swing.JLabel();
        j8 = new javax.swing.JPanel();
        tableNumber9 = new javax.swing.JLabel();
        j9 = new javax.swing.JPanel();
        tableNumber10 = new javax.swing.JLabel();
        j10 = new javax.swing.JPanel();
        tableNumber11 = new javax.swing.JLabel();
        j11 = new javax.swing.JPanel();
        tableNumber12 = new javax.swing.JLabel();
        j12 = new javax.swing.JPanel();
        tableNumber13 = new javax.swing.JLabel();
        j13 = new javax.swing.JPanel();
        tableNumber14 = new javax.swing.JLabel();
        j14 = new javax.swing.JPanel();
        tableNumber15 = new javax.swing.JLabel();
        j15 = new javax.swing.JPanel();
        tableNumber16 = new javax.swing.JLabel();
        j16 = new javax.swing.JPanel();
        tableNumber17 = new javax.swing.JLabel();
        j17 = new javax.swing.JPanel();
        tableNumber18 = new javax.swing.JLabel();
        j18 = new javax.swing.JPanel();
        tableNumber19 = new javax.swing.JLabel();
        j19 = new javax.swing.JPanel();
        tableNumber20 = new javax.swing.JLabel();
        j20 = new javax.swing.JPanel();
        tableNumber21 = new javax.swing.JLabel();
        j21 = new javax.swing.JPanel();
        tableNumber22 = new javax.swing.JLabel();
        j22 = new javax.swing.JPanel();
        tableNumber23 = new javax.swing.JLabel();
        j23 = new javax.swing.JPanel();
        tableNumber24 = new javax.swing.JLabel();
        j24 = new javax.swing.JPanel();
        tableNumber25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzeria");
        setResizable(false);

        mainFrame.setBackground(new java.awt.Color(153, 255, 204));
        mainFrame.setText("Main Frame");
        mainFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrameActionPerformed(evt);
            }
        });

        tableCollection.setLayout(new java.awt.GridLayout(5, 7));

        table.setBackground(new java.awt.Color(153, 153, 255));
        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setToolTipText("");
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onMouseClicked(evt);
            }
        });

        tableNumber.setText("0");
        tableNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(tableNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tableNumber)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tableCollection.add(table);

        j1.setToolTipText(" ");

        tableNumber1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber1onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j1Layout = new javax.swing.GroupLayout(j1);
        j1.setLayout(j1Layout);
        j1Layout.setHorizontalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j1Layout.setVerticalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j1);

        tableNumber2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber2onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j2Layout = new javax.swing.GroupLayout(j2);
        j2.setLayout(j2Layout);
        j2Layout.setHorizontalGroup(
            j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j2Layout.setVerticalGroup(
            j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber2)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j2);

        tableNumber3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber3onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j3Layout = new javax.swing.GroupLayout(j3);
        j3.setLayout(j3Layout);
        j3Layout.setHorizontalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j3Layout.setVerticalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber3)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j3);

        tableNumber4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber4onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j4Layout = new javax.swing.GroupLayout(j4);
        j4.setLayout(j4Layout);
        j4Layout.setHorizontalGroup(
            j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j4Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j4Layout.setVerticalGroup(
            j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber4)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j4);

        tableNumber5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber5onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j5Layout = new javax.swing.GroupLayout(j5);
        j5.setLayout(j5Layout);
        j5Layout.setHorizontalGroup(
            j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j5Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j5Layout.setVerticalGroup(
            j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber5)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j5);

        tableNumber6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber6onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j6Layout = new javax.swing.GroupLayout(j6);
        j6.setLayout(j6Layout);
        j6Layout.setHorizontalGroup(
            j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j6Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j6Layout.setVerticalGroup(
            j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber6)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j6);

        tableNumber7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber7onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j7Layout = new javax.swing.GroupLayout(j7);
        j7.setLayout(j7Layout);
        j7Layout.setHorizontalGroup(
            j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j7Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j7Layout.setVerticalGroup(
            j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber7)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j7);

        tableNumber9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber9onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j8Layout = new javax.swing.GroupLayout(j8);
        j8.setLayout(j8Layout);
        j8Layout.setHorizontalGroup(
            j8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j8Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j8Layout.setVerticalGroup(
            j8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber9)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j8);

        tableNumber10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber10onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j9Layout = new javax.swing.GroupLayout(j9);
        j9.setLayout(j9Layout);
        j9Layout.setHorizontalGroup(
            j9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j9Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j9Layout.setVerticalGroup(
            j9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber10)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j9);

        tableNumber11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber11onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j10Layout = new javax.swing.GroupLayout(j10);
        j10.setLayout(j10Layout);
        j10Layout.setHorizontalGroup(
            j10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j10Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j10Layout.setVerticalGroup(
            j10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j10Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber11)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j10);

        tableNumber12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber12onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j11Layout = new javax.swing.GroupLayout(j11);
        j11.setLayout(j11Layout);
        j11Layout.setHorizontalGroup(
            j11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j11Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j11Layout.setVerticalGroup(
            j11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j11Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber12)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j11);

        tableNumber13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber13onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j12Layout = new javax.swing.GroupLayout(j12);
        j12.setLayout(j12Layout);
        j12Layout.setHorizontalGroup(
            j12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j12Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j12Layout.setVerticalGroup(
            j12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j12Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber13)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j12);

        tableNumber14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber14onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j13Layout = new javax.swing.GroupLayout(j13);
        j13.setLayout(j13Layout);
        j13Layout.setHorizontalGroup(
            j13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j13Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j13Layout.setVerticalGroup(
            j13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j13Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber14)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j13);

        tableNumber15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber15onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j14Layout = new javax.swing.GroupLayout(j14);
        j14.setLayout(j14Layout);
        j14Layout.setHorizontalGroup(
            j14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j14Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j14Layout.setVerticalGroup(
            j14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j14Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber15)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j14);

        tableNumber16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber16onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j15Layout = new javax.swing.GroupLayout(j15);
        j15.setLayout(j15Layout);
        j15Layout.setHorizontalGroup(
            j15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j15Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j15Layout.setVerticalGroup(
            j15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j15Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber16)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j15);

        tableNumber17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber17onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j16Layout = new javax.swing.GroupLayout(j16);
        j16.setLayout(j16Layout);
        j16Layout.setHorizontalGroup(
            j16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j16Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j16Layout.setVerticalGroup(
            j16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j16Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber17)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j16);

        tableNumber18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber18onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j17Layout = new javax.swing.GroupLayout(j17);
        j17.setLayout(j17Layout);
        j17Layout.setHorizontalGroup(
            j17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j17Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j17Layout.setVerticalGroup(
            j17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j17Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber18)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j17);

        tableNumber19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber19onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j18Layout = new javax.swing.GroupLayout(j18);
        j18.setLayout(j18Layout);
        j18Layout.setHorizontalGroup(
            j18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j18Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j18Layout.setVerticalGroup(
            j18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j18Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber19)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j18);

        tableNumber20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber20onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j19Layout = new javax.swing.GroupLayout(j19);
        j19.setLayout(j19Layout);
        j19Layout.setHorizontalGroup(
            j19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j19Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j19Layout.setVerticalGroup(
            j19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j19Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber20)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j19);

        tableNumber21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber21onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j20Layout = new javax.swing.GroupLayout(j20);
        j20.setLayout(j20Layout);
        j20Layout.setHorizontalGroup(
            j20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j20Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j20Layout.setVerticalGroup(
            j20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j20Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber21)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j20);

        tableNumber22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber22onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j21Layout = new javax.swing.GroupLayout(j21);
        j21.setLayout(j21Layout);
        j21Layout.setHorizontalGroup(
            j21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j21Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j21Layout.setVerticalGroup(
            j21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j21Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber22)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j21);

        tableNumber23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber23onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j22Layout = new javax.swing.GroupLayout(j22);
        j22.setLayout(j22Layout);
        j22Layout.setHorizontalGroup(
            j22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j22Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j22Layout.setVerticalGroup(
            j22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j22Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber23)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j22);

        tableNumber24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber24onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j23Layout = new javax.swing.GroupLayout(j23);
        j23.setLayout(j23Layout);
        j23Layout.setHorizontalGroup(
            j23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j23Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j23Layout.setVerticalGroup(
            j23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j23Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber24)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j23);

        j24.setToolTipText(" ");

        tableNumber25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNumber25onLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout j24Layout = new javax.swing.GroupLayout(j24);
        j24.setLayout(j24Layout);
        j24Layout.setHorizontalGroup(
            j24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j24Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(tableNumber25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j24Layout.setVerticalGroup(
            j24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j24Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(tableNumber25)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        tableCollection.add(j24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tableCollection, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseClicked
        // TODO add your handling code here:
        new PaymentFrame(ct, Integer.parseInt(this.tableNumber.getText().toString())).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_onMouseClicked

    private void mainFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainFrameActionPerformed
        // TODO add your handling code here:
        new MainFrame(ct).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mainFrameActionPerformed

    private void onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_onLabelClicked

    private void tableNumber1onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber1onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber1onLabelClicked

    private void tableNumber2onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber2onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber2onLabelClicked

    private void tableNumber3onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber3onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber3onLabelClicked

    private void tableNumber4onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber4onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber4onLabelClicked

    private void tableNumber5onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber5onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber5onLabelClicked

    private void tableNumber6onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber6onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber6onLabelClicked

    private void tableNumber7onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber7onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber7onLabelClicked

    private void tableNumber9onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber9onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber9onLabelClicked

    private void tableNumber10onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber10onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber10onLabelClicked

    private void tableNumber11onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber11onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber11onLabelClicked

    private void tableNumber12onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber12onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber12onLabelClicked

    private void tableNumber13onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber13onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber13onLabelClicked

    private void tableNumber14onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber14onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber14onLabelClicked

    private void tableNumber15onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber15onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber15onLabelClicked

    private void tableNumber16onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber16onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber16onLabelClicked

    private void tableNumber17onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber17onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber17onLabelClicked

    private void tableNumber18onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber18onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber18onLabelClicked

    private void tableNumber19onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber19onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber19onLabelClicked

    private void tableNumber20onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber20onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber20onLabelClicked

    private void tableNumber21onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber21onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber21onLabelClicked

    private void tableNumber22onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber22onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber22onLabelClicked

    private void tableNumber23onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber23onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber23onLabelClicked

    private void tableNumber24onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber24onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber24onLabelClicked

    private void tableNumber25onLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNumber25onLabelClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumber25onLabelClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActiveTablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActiveTablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActiveTablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActiveTablesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ActiveTablesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel j1;
    private javax.swing.JPanel j10;
    private javax.swing.JPanel j11;
    private javax.swing.JPanel j12;
    private javax.swing.JPanel j13;
    private javax.swing.JPanel j14;
    private javax.swing.JPanel j15;
    private javax.swing.JPanel j16;
    private javax.swing.JPanel j17;
    private javax.swing.JPanel j18;
    private javax.swing.JPanel j19;
    private javax.swing.JPanel j2;
    private javax.swing.JPanel j20;
    private javax.swing.JPanel j21;
    private javax.swing.JPanel j22;
    private javax.swing.JPanel j23;
    private javax.swing.JPanel j24;
    private javax.swing.JPanel j3;
    private javax.swing.JPanel j4;
    private javax.swing.JPanel j5;
    private javax.swing.JPanel j6;
    private javax.swing.JPanel j7;
    private javax.swing.JPanel j8;
    private javax.swing.JPanel j9;
    private javax.swing.JButton mainFrame;
    private javax.swing.JPanel table;
    private javax.swing.JPanel tableCollection;
    private javax.swing.JLabel tableNumber;
    private javax.swing.JLabel tableNumber1;
    private javax.swing.JLabel tableNumber10;
    private javax.swing.JLabel tableNumber11;
    private javax.swing.JLabel tableNumber12;
    private javax.swing.JLabel tableNumber13;
    private javax.swing.JLabel tableNumber14;
    private javax.swing.JLabel tableNumber15;
    private javax.swing.JLabel tableNumber16;
    private javax.swing.JLabel tableNumber17;
    private javax.swing.JLabel tableNumber18;
    private javax.swing.JLabel tableNumber19;
    private javax.swing.JLabel tableNumber2;
    private javax.swing.JLabel tableNumber20;
    private javax.swing.JLabel tableNumber21;
    private javax.swing.JLabel tableNumber22;
    private javax.swing.JLabel tableNumber23;
    private javax.swing.JLabel tableNumber24;
    private javax.swing.JLabel tableNumber25;
    private javax.swing.JLabel tableNumber3;
    private javax.swing.JLabel tableNumber4;
    private javax.swing.JLabel tableNumber5;
    private javax.swing.JLabel tableNumber6;
    private javax.swing.JLabel tableNumber7;
    private javax.swing.JLabel tableNumber9;
    // End of variables declaration//GEN-END:variables

    private void addPanels() {
        panels.add(this.table);
        panels.add(j1);
        panels.add(j2);
        panels.add(j3);
        panels.add(j4);
        panels.add(j5);
        panels.add(j6);
        panels.add(j7);
        panels.add(j8);
        panels.add(j9);
        panels.add(j10);
        panels.add(j11);
        panels.add(j12);
        panels.add(j13);
        panels.add(j14);
        panels.add(j15);
        panels.add(j16);
        panels.add(j17);
        panels.add(j18);
        panels.add(j19);
        panels.add(j20);
        
    }

    private void addLabels() {
        labels.add(this.tableNumber);
        labels.add(this.tableNumber1);
        labels.add(this.tableNumber2);
        labels.add(this.tableNumber3);
        labels.add(this.tableNumber4);
        labels.add(this.tableNumber5);
        labels.add(this.tableNumber6);
        labels.add(this.tableNumber7);
        labels.add(this.tableNumber9);
        labels.add(this.tableNumber10);
        labels.add(this.tableNumber11);
        labels.add(this.tableNumber12);
        labels.add(this.tableNumber13);
        labels.add(this.tableNumber14);
        labels.add(this.tableNumber15);
        labels.add(this.tableNumber16);
        labels.add(this.tableNumber17);
        labels.add(this.tableNumber18);
        labels.add(this.tableNumber19);
        labels.add(this.tableNumber20);
        labels.add(this.tableNumber21);
    }
}
